### ISSUE TITLE
Compilation error on Fedora

### ISSUE THREAD

**Issue by verdurin** [arq5x/bedtools2#267]
I'm updating the Fedora RPM to 2.24.0. In a test build, the i386 version fails with an error during compilation (listed below). The current GCC version for the development tree in Fedora is 5.1.1.
```
- Building in src/utils/tabFile
  * compiling tabFile.cpp
In file included from FileRecordMgr.h:12:0,
                 from FileRecordMgr.cpp:2:
../../utils//general/QuickString.h:41:15: error: 'QuickString& QuickString::operator=(size_t)' cannot be overloaded
  QuickString &operator = (size_t);
               ^
../../utils//general/QuickString.h:40:15: error: with 'QuickString& QuickString::operator=(uint32_t)'
  QuickString &operator = (uint32_t);
               ^
../../utils//general/QuickString.h:50:15: error: 'QuickString& QuickString::operator+=(size_t)' cannot be overloaded
  QuickString &operator += (size_t);
               ^
../../utils//general/QuickString.h:49:15: error: with 'QuickString& QuickString::operator+=(uint32_t)'
  QuickString &operator += (uint32_t);
               ^
../../utils//general/QuickString.h:76:7: error: 'void QuickString::append(size_t)' cannot be overloaded
  void append(size_t num);
       ^
../../utils//general/QuickString.h:75:7: error: with 'void QuickString::append(uint32_t)'
  void append(uint32_t num);
       ^
In file included from KeyListOpsMethods.h:13:0,
                 from KeyListOps.h:11,
                 from KeyListOps.cpp:7:
../../utils//general/QuickString.h:41:15: error: 'QuickString& QuickString::operator=(size_t)' cannot be overloaded
  QuickString &operator = (size_t);
               ^
../../utils//general/QuickString.h:40:15: error: with 'QuickString& QuickString::operator=(uint32_t)'
  QuickString &operator = (uint32_t);
               ^
../../utils//general/QuickString.h:50:15: error: 'QuickString& QuickString::operator+=(size_t)' cannot be overloaded
  QuickString &operator += (size_t);
               ^
../../utils//general/QuickString.h:49:15: error: with 'QuickString& QuickString::operator+=(uint32_t)'
  QuickString &operator += (uint32_t);
               ^
../../utils//general/QuickString.h:76:7: error: 'void QuickString::append(size_t)' cannot be overloaded
  void append(size_t num);
       ^
../../utils//general/QuickString.h:75:7: error: with 'void QuickString::append(uint32_t)'
  void append(uint32_t num);
       ^
In file included from ../../utils//general/BedtoolsTypes.h:20:0,
                 from ContextBase.h:21,
                 from ContextIntersect.h:11,
                 from ContextIntersect.cpp:8:
../../utils//general/QuickString.h:41:15: error: 'QuickString& QuickString::operator=(size_t)' cannot be overloaded
  QuickString &operator = (size_t);
               ^
../../utils//general/QuickString.h:40:15: error: with 'QuickString& QuickString::operator=(uint32_t)'
  QuickString &operator = (uint32_t);
               ^
../../utils//general/QuickString.h:50:15: error: 'QuickString& QuickString::operator+=(size_t)' cannot be overloaded
  QuickString &operator += (size_t);
               ^
../../utils//general/QuickString.h:49:15: error: with 'QuickString& QuickString::operator+=(uint32_t)'
  QuickString &operator += (uint32_t);
               ^
../../utils//general/QuickString.h:76:7: error: 'void QuickString::append(size_t)' cannot be overloaded
  void append(size_t num);
       ^
../../utils//general/QuickString.h:75:7: error: with 'void QuickString::append(uint32_t)'
  void append(uint32_t num);
       ^
In file included from BinTree.h:16:0,
                 from BinTree.cpp:1:
../../utils//general/QuickString.h:41:15: error: 'QuickString& QuickString::operator=(size_t)' cannot be overloaded
  QuickString &operator = (size_t);
               ^
../../utils//general/QuickString.h:40:15: error: with 'QuickString& QuickString::operator=(uint32_t)'
  QuickString &operator = (uint32_t);
               ^
../../utils//general/QuickString.h:50:15: error: 'QuickString& QuickString::operator+=(size_t)' cannot be overloaded
  QuickString &operator += (size_t);
               ^
../../utils//general/QuickString.h:49:15: error: with 'QuickString& QuickString::operator+=(uint32_t)'
  QuickString &operator += (uint32_t);
               ^
../../utils//general/QuickString.h:76:7: error: 'void QuickString::append(size_t)' cannot be overloaded
  void append(size_t num);
       ^
../../utils//general/QuickString.h:75:7: error: with 'void QuickString::append(uint32_t)'
  void append(uint32_t num);
       ^
In file included from FileReader.h:7:0,
                 from FileReader.cpp:3:
../../../utils//general/QuickString.h:41:15: error: 'QuickString& QuickString::operator=(size_t)' cannot be overloaded
  QuickString &operator = (size_t);
               ^
../../../utils//general/QuickString.h:40:15: error: with 'QuickString& QuickString::operator=(uint32_t)'
  QuickString &operator = (uint32_t);
               ^
../../../utils//general/QuickString.h:50:15: error: 'QuickString& QuickString::operator+=(size_t)' cannot be overloaded
  QuickString &operator += (size_t);
               ^
../../../utils//general/QuickString.h:49:15: error: with 'QuickString& QuickString::operator+=(uint32_t)'
  QuickString &operator += (uint32_t);
               ^
../../../utils//general/QuickString.h:76:7: error: 'void QuickString::append(size_t)' cannot be overloaded
  void append(size_t num);
       ^
../../../utils//general/QuickString.h:75:7: error: with 'void QuickString::append(uint32_t)'
  void append(uint32_t num);
       ^
  * compiling FileRecordTypeChecker.cpp
- Building in src/utils/BamTools
In file included from ../../utils//general/BTlist.h:29:0,
                 from NewChromsweep.h:16,
                 from NewChromsweep.cpp:13:
../../utils//general/QuickString.h:41:15: error: 'QuickString& QuickString::operator=(size_t)' cannot be overloaded
  QuickString &operator = (size_t);
               ^
../../utils//general/QuickString.h:40:15: error: with 'QuickString& QuickString::operator=(uint32_t)'
  QuickString &operator = (uint32_t);
               ^
../../utils//general/QuickString.h:50:15: error: 'QuickString& QuickString::operator+=(size_t)' cannot be overloaded
  QuickString &operator += (size_t);
               ^
../../utils//general/QuickString.h:49:15: error: with 'QuickString& QuickString::operator+=(uint32_t)'
  QuickString &operator += (uint32_t);
               ^
../../utils//general/QuickString.h:76:7: error: 'void QuickString::append(size_t)' cannot be overloaded
  void append(size_t num);
       ^
../../utils//general/QuickString.h:75:7: error: with 'void QuickString::append(uint32_t)'
  void append(uint32_t num);
       ^
 * compiling BamAlignment.cpp
Makefile:33: recipe for target '../../../../obj//FileReader.o' failed
make[1]: *** [../../../../obj//FileReader.o] Error 1
Makefile:176: recipe for target 'src/utils/FileRecordTools/FileReaders' failed
make: *** [src/utils/FileRecordTools/FileReaders] Error 2
make: *** Waiting for unfinished jobs....
 * compiling BamMultiReader.cpp
In file included from QuickString.cpp:1:0:
QuickString.h:41:15: error: 'QuickString& QuickString::operator=(size_t)' cannot be overloaded
  QuickString &operator = (size_t);
               ^
QuickString.h:40:15: error: with 'QuickString& QuickString::operator=(uint32_t)'
  QuickString &operator = (uint32_t);
               ^
QuickString.h:50:15: error: 'QuickString& QuickString::operator+=(size_t)' cannot be overloaded
  QuickString &operator += (size_t);
               ^
QuickString.h:49:15: error: with 'QuickString& QuickString::operator+=(uint32_t)'
  QuickString &operator += (uint32_t);
               ^
QuickString.h:76:7: error: 'void QuickString::append(size_t)' cannot be overloaded
  void append(size_t num);
       ^
QuickString.h:75:7: error: with 'void QuickString::append(uint32_t)'
  void append(uint32_t num);
       ^
In file included from Record.h:13:0,
                 from Record.cpp:2:
../../../utils//general/QuickString.h:41:15: error: 'QuickString& QuickString::operator=(size_t)' cannot be overloaded
  QuickString &operator = (size_t);
               ^
../../../utils//general/QuickString.h:40:15: error: with 'QuickString& QuickString::operator=(uint32_t)'
  QuickString &operator = (uint32_t);
               ^
../../../utils//general/QuickString.h:50:15: error: 'QuickString& QuickString::operator+=(size_t)' cannot be overloaded
  QuickString &operator += (size_t);
               ^
../../../utils//general/QuickString.h:49:15: error: with 'QuickString& QuickString::operator+=(uint32_t)'
  QuickString &operator += (uint32_t);
               ^
../../../utils//general/QuickString.h:76:7: error: 'void QuickString::append(size_t)' cannot be overloaded
  void append(size_t num);
       ^
../../../utils//general/QuickString.h:75:7: error: with 'void QuickString::append(uint32_t)'
  void append(uint32_t num);
       ^
Makefile:35: recipe for target '../../../obj//FileRecordMgr.o' failed
make[1]: *** [../../../obj//FileRecordMgr.o] Error 1
Makefile:176: recipe for target 'src/utils/FileRecordTools' failed
make: *** [src/utils/FileRecordTools] Error 2
 * compiling BamReader.cpp
Makefile:36: recipe for target '../../../obj//ContextIntersect.o' failed
make[1]: *** [../../../obj//ContextIntersect.o] Error 1
make[1]: *** Waiting for unfinished jobs....
 * compiling BamWriter.cpp
In file included from ../../utils//general/BedtoolsTypes.h:20:0,
                 from ContextBase.h:21,
                 from ContextBase.cpp:8:
../../utils//general/QuickString.h:41:15: error: 'QuickString& QuickString::operator=(size_t)' cannot be overloaded
  QuickString &operator = (size_t);
               ^
../../utils//general/QuickString.h:40:15: error: with 'QuickString& QuickString::operator=(uint32_t)'
  QuickString &operator = (uint32_t);
               ^
../../utils//general/QuickString.h:50:15: error: 'QuickString& QuickString::operator+=(size_t)' cannot be overloaded
  QuickString &operator += (size_t);
               ^
../../utils//general/QuickString.h:49:15: error: with 'QuickString& QuickString::operator+=(uint32_t)'
  QuickString &operator += (uint32_t);
               ^
../../utils//general/QuickString.h:76:7: error: 'void QuickString::append(size_t)' cannot be overloaded
  void append(size_t num);
       ^
../../utils//general/QuickString.h:75:7: error: with 'void QuickString::append(uint32_t)'
  void append(uint32_t num);
       ^
QuickString.cpp:108:14: error: redefinition of 'QuickString& QuickString::operator=(size_t)'
 QuickString &QuickString::operator = (size_t val) {
              ^
QuickString.cpp:102:14: note: 'QuickString& QuickString::operator=(uint32_t)' previously defined here
 QuickString &QuickString::operator = (uint32_t val) {
              ^
QuickString.cpp:161:14: error: redefinition of 'QuickString& QuickString::operator+=(size_t)'
 QuickString &QuickString::operator += (size_t num) {
              ^
QuickString.cpp:156:14: note: 'QuickString& QuickString::operator+=(uint32_t)' previously defined here
 QuickString &QuickString::operator += (uint32_t num) {
              ^
QuickString.cpp:267:6: error: redefinition of 'void QuickString::append(size_t)'
 void QuickString::append(size_t num) {
      ^
QuickString.cpp:263:6: note: 'void QuickString::append(uint32_t)' previously defined here
 void QuickString::append(uint32_t num) {
      ^
Makefile:37: recipe for target '../../../../obj//Record.o' failed
make[1]: *** [../../../../obj//Record.o] Error 1
Makefile:176: recipe for target 'src/utils/FileRecordTools/Records' failed
make: *** [src/utils/FileRecordTools/Records] Error 2
 * compiling SamHeader.cpp
Makefile:32: recipe for target '../../../obj//KeyListOps.o' failed
make[1]: *** [../../../obj//KeyListOps.o] Error 1
make: *** [src/utils/KeyListOps] Error 2
Makefile:176: recipe for target 'src/utils/KeyListOps' failed
  * compiling ParseTools.cpp
In file included from ../../utils//general/BTlist.h:29:0,
                 from ../../utils//general/PushBackStreamBuf.h:12,
                 from FileRecordTypeChecker.h:18,
                 from FileRecordTypeChecker.cpp:2:
../../utils//general/QuickString.h:41:15: error: 'QuickString& QuickString::operator=(size_t)' cannot be overloaded
  QuickString &operator = (size_t);
               ^
../../utils//general/QuickString.h:40:15: error: with 'QuickString& QuickString::operator=(uint32_t)'
  QuickString &operator = (uint32_t);
               ^
../../utils//general/QuickString.h:50:15: error: 'QuickString& QuickString::operator+=(size_t)' cannot be overloaded
  QuickString &operator += (size_t);
               ^
../../utils//general/QuickString.h:49:15: error: with 'QuickString& QuickString::operator+=(uint32_t)'
  QuickString &operator += (uint32_t);
               ^
../../utils//general/QuickString.h:76:7: error: 'void QuickString::append(size_t)' cannot be overloaded
  void append(size_t num);
       ^
../../utils//general/QuickString.h:75:7: error: with 'void QuickString::append(uint32_t)'
  void append(uint32_t num);
       ^
Makefile:23: recipe for target '../../../obj//QuickString.o' failed
make[1]: *** [../../../obj//QuickString.o] Error 1
make[1]: *** Waiting for unfinished jobs....
 * compiling SamProgram.cpp
Makefile:29: recipe for target '../../../obj//BinTree.o' failed
make[1]: *** [../../../obj//BinTree.o] Error 1
Makefile:176: recipe for target 'src/utils/BinTree' failed
make: *** [src/utils/BinTree] Error 2
 * compiling SamProgramChain.cpp
Makefile:24: recipe for target '../../../obj//FileRecordTypeChecker.o' failed
make[1]: *** [../../../obj//FileRecordTypeChecker.o] Error 1
make: *** [src/utils/fileType] Error 2
Makefile:176: recipe for target 'src/utils/fileType' failed
 * compiling SamReadGroup.cpp
In file included from ParseTools.h:15:0,
                 from ParseTools.cpp:1:
QuickString.h:41:15: error: 'QuickString& QuickString::operator=(size_t)' cannot be overloaded
  QuickString &operator = (size_t);
               ^
QuickString.h:40:15: error: with 'QuickString& QuickString::operator=(uint32_t)'
  QuickString &operator = (uint32_t);
               ^
QuickString.h:50:15: error: 'QuickString& QuickString::operator+=(size_t)' cannot be overloaded
  QuickString &operator += (size_t);
               ^
QuickString.h:49:15: error: with 'QuickString& QuickString::operator+=(uint32_t)'
  QuickString &operator += (uint32_t);
               ^
QuickString.h:76:7: error: 'void QuickString::append(size_t)' cannot be overloaded
  void append(size_t num);
       ^
QuickString.h:75:7: error: with 'void QuickString::append(uint32_t)'
  void append(uint32_t num);
       ^
 * compiling SamReadGroupDictionary.cpp
ParseTools.cpp: In function 'int str2chrPos(const char*, size_t)':
ParseTools.cpp:31:7: warning: unused variable 'hasExponent' [-Wunused-variable]
  bool hasExponent = false;
       ^
Makefile:23: recipe for target '../../../obj//ParseTools.o' failed
make[1]: *** [../../../obj//ParseTools.o] Error 1
make: *** [src/utils/general] Error 2
Makefile:176: recipe for target 'src/utils/general' failed
 * compiling SamSequence.cpp
Makefile:36: recipe for target '../../../obj//ContextBase.o' failed
make[1]: *** [../../../obj//ContextBase.o] Error 1
Makefile:176: recipe for target 'src/utils/Contexts' failed
make: *** [src/utils/Contexts] Error 2
 * compiling SamSequenceDictionary.cpp
Makefile:35: recipe for target '../../../obj//NewChromsweep.o' failed
make[1]: *** [../../../obj//NewChromsweep.o] Error 1
make: *** [src/utils/NewChromsweep] Error 2
Makefile:176: recipe for target 'src/utils/NewChromsweep' failed
 * compiling BamHeader_p.cpp
 * compiling BamMultiReader_p.cpp
 * compiling BamReader_p.cpp
 * compiling BamRandomAccessController_p.cpp
 * compiling BamWriter_p.cpp
 * compiling BamIndexFactory_p.cpp
 * compiling BamStandardIndex_p.cpp
 * compiling BamToolsIndex_p.cpp
 * compiling BamDeviceFactory_p.cpp
 * compiling BamFile_p.cpp
 * compiling BamFtp_p.cpp
 * compiling BamHttp_p.cpp
 * compiling BamPipe_p.cpp
 * compiling BgzfStream_p.cpp
 * compiling ByteArray_p.cpp
 * compiling HostAddress_p.cpp
 * compiling HostInfo_p.cpp
 * compiling HttpHeader_p.cpp
 * compiling ILocalIODevice_p.cpp
 * compiling RollingBuffer_p.cpp
 * compiling TcpSocketEngine_p.cpp
 * compiling TcpSocketEngine_unix_p.cpp
 * compiling TcpSocket_p.cpp
 * compiling SamFormatParser_p.cpp
 * compiling SamFormatPrinter_p.cpp
 * compiling SamHeaderValidator_p.cpp
 * compiling BamException_p.cpp
 * linking lib/libbamtools.a
ar cr lib/libbamtools.a src/api/BamAlignment.o src/api/BamMultiReader.o src/api/BamReader.o src/api/BamWriter.o src/api/SamHeader.o src/api/SamProgram.o src/api/SamProgramChain.o src/api/SamReadGroup.o src/api/SamReadGroupDictionary.o src/api/SamSequence.o src/api/SamSequenceDictionary.o src/api/internal/bam/BamHeader_p.o src/api/internal/bam/BamMultiReader_p.o src/api/internal/bam/BamRandomAccessController_p.o src/api/internal/bam/BamReader_p.o src/api/internal/bam/BamWriter_p.o src/api/internal/index/BamIndexFactory_p.o src/api/internal/index/BamStandardIndex_p.o src/api/internal/index/BamToolsIndex_p.o src/api/internal/io/BamDeviceFactory_p.o src/api/internal/io/BamFile_p.o src/api/internal/io/BamFtp_p.o src/api/internal/io/BamHttp_p.o src/api/internal/io/BamPipe_p.o src/api/internal/io/BgzfStream_p.o src/api/internal/io/ByteArray_p.o src/api/internal/io/HostAddress_p.o src/api/internal/io/HostInfo_p.o src/api/internal/io/HttpHeader_p.o src/api/internal/io/ILocalIODevice_p.o src/api/internal/io/RollingBuffer_p.o src/api/internal/io/TcpSocketEngine_p.o src/api/internal/io/TcpSocketEngine_unix_p.o src/api/internal/io/TcpSocket_p.o src/api/internal/sam/SamFormatParser_p.o src/api/internal/sam/SamFormatPrinter_p.o src/api/internal/sam/SamHeaderValidator_p.o src/api/internal/utils/BamException_p.o
ranlib lib/libbamtools.a
error: Bad exit status from /var/tmp/rpm-tmp.kwQN4M (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.kwQN4M (%build)
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target i686 --nodeps  /builddir/build/SPECS/BEDTools.spec 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 494, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target i686 --nodeps  /builddir/build/SPECS/BEDTools.spec 
LEAVE do --> EXCEPTION RAISED
```

**Comment by nkindlon** [comment]
It looks like your compiler is complaining that uint32_t and size_t can't be treated as separate types. That's odd, since they are different, depending on the system. Here's a thread about it:
http://stackoverflow.com/questions/918787/whats-sizeofsize-t-on-32-bit-vs-the-various-64-bit-data-models

I'm not sure the best way to fix that, but found another thread suggesting the use of the boost library's enable_if to get a compile-time solution (vs. a run time solution):
http://stackoverflow.com/questions/10579544/ambiguous-overload-of-functions-like-msglong-with-candidates-msgint32-t

Unforuntately, I'm no longer with the lab, and Aaron's pretty swamped, but I'll mention this to him to see if he wants to try this.
-Neil

**Comment by verdurin** [comment]
@nkindlon - thanks for taking a look.

I can add a patch to fix compilation for Fedora, but it's clearly better if this is fixed upstream. The same problem would probably occur on the other distros when they pick up that GCC version too.

**Comment by arq5x** [comment]
It looks like this is a simple fix as the compiler is complaining that to it, there are two identical function signatures, one for `size_t` and one for `uint32_t`. 

@nkindlon - I think we just need one or the other correct?

**Comment by arq5x** [comment]
I think commit b47dbefcb5 should address this.  Could you clone and try to compile? If it still fails, please reopen.  Sorry, I don't have debian to test.

**Comment by verdurin** [comment]
@arq5x - Yes, this fixes it. I've included your patch and will remove it after your next release.

Many thanks.
